### PR TITLE
making it usable even if you you aren't in the russian timezone

### PR DESCRIPTION
**Pull request by ghost**
fixes: 
image

yeah.... that's it

### CODE REVIEW

**Comment by ghost** [comment]
so we "american suckers" can have some fun too :)

**Comment by LkPrtctrd** [comment]
now adjust it to 11 o'clock in russian format🙃

**Comment by LkPrtctrd** [comment]
and why didn't you do the same for the original project? https://github.com/XidMods05/brawl-stars-v36-private-server

**Comment by ghost** [comment]
> and why didn't you do the same for the original project? https://github.com/XidMods05/brawl-stars-v36-private-server

didn't think of it tbh

**Comment by ghost** [comment]
> now adjust it to 11 o'clock in russian format🙃

wdym?

**Comment by us259er** [comment]
> and why didn't you do the same for the original project? https://github.com/XidMods05/brawl-stars-v36-private-server

the original project is bad... really bad
if i were to write a server i would have made my own server with dependency injection or use xeon's core

**Pull request closed without merging**
